# Generated by Django 5.0.7 on 2024-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
