# Generated by Django 5.0.7 on 2024-08-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogmodel_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(max_length=1000, upload_to=''),
        ),
    ]
